- NetKAN/BetterPartsManager.netkan
- NetKAN/CheatsMenu.netkan
- NetKAN/CommunityFixes.netkan
- NetKAN/KerbalNotebook.netkan
- NetKAN/KerbalWebProgram.netkan
- NetKAN/MoreResolutions.netkan
- NetKAN/PaigeBGone.netkan
- NetKAN/PartsManagerHotkey.netkan
- NetKAN/StageInfo.netkan
- NetKAN/kRPC2.netkan
These mods were previously requested from SpaceDock (which went to the old KSP1 repo, because SpaceDock's "support" for KSP2+CKAN is a bug).
- KSP-CKAN/NetKAN#9597
https://spacedock.info/mod/3266/Cheats%20Menu
https://github.com/Bit-Studios/CheatMenu
https://forum.kerbalspaceprogram.com/index.php?/topic/214242-cheat-menu/
- KSP-CKAN/NetKAN#9598
https://spacedock.info/mod/3292/Better%20Parts%20Manager
https://github.com/Bit-Studios/KerbalPartManager
https://forum.kerbalspaceprogram.com/index.php?/topic/214227-better-part-manager/
- KSP-CKAN/NetKAN#9600
https://spacedock.info/mod/3272/Stage%20Info
- KSP-CKAN/NetKAN#9605
https://spacedock.info/mod/3301/Community%20Fixes
https://github.com/Bit-Studios/CommunityFixes
https://forum.kerbalspaceprogram.com/index.php?/topic/214521-community-fixes/ …
> Catch up with mods submitted from SpaceDock

- NetKAN/CustomFlags.netkan
- <https://spacedock.info/mod/3262/Custom%20Flags>
- <https://github.com/adamsong/custom-flags>
> add CustomFlags.netkan

- NetKAN/PaigeBGone.netkan
This mod's author requested indexing from GitHub in <https://github.com/KSP-CKAN/NetKAN/pull/9617#issuecomment-1464860394>, and I forgot to also add `resources.spacedock` for completeness. Now it's added.
> Add PaigeBGone SpaceDock link

- NetKAN/Kalkulator.netkan
- NetKAN/SpaceWarp.netkan
Migrated from KSP-CKAN/NetKAN#9624
___
ckan compat add 0.1.0
> Add Kalkulator

- NetKAN/BurnController.netkan
Replaces KSP-CKAN/NetKAN#9627
___
ckan compat add 0.1.0
> Add BurnController

- NetKAN/SpeedyStartup.netkan
Since SpaceDock's CKAN button is broken for KSP2 mods, I'll do this manually for now
___
ckan compat add 0.1.0
> Add Speedy Startup

- NetKAN/EVAAnarchy.netkan
- <https://spacedock.info/mod/3341/EVA%20Anarchy>
- <https://github.com/ThunderousEcho/EvaAnarchy>
Closes KSP-CKAN/NetKAN#9635.
___
ckan compat add 0.1.0
> Add EVAAnarchy

- NetKAN/MicroEngineer.netkan
- <https://spacedock.info/mod/3282/Micro%20Engineer>
- <https://github.com/Micrologist/MicroEngineer>
Closes KSP-CKAN/NetKAN#9636.
> Add MicroEngineer

- NetKAN/LuxsOABExtensions.netkan
- <https://spacedock.info/mod/3354/Lux's%20OAB%20Extensions>
- <https://forum.kerbalspaceprogram.com/index.php?/topic/216276-luxs-oab-extensions-010-more-symmetry-options-custom-size-labels-mk2-mk3-are-back/>
Fixes KSP-CKAN/NetKAN#9652.
> Add LuxsOABExtensions

- NetKAN/CountDown.netkan
Add ShadowUtilityLIB for next release of this mod.
> Update dependency for next version

- NetKAN/KerbalNotebook.netkan
Basically starting to feel like this https://youtu.be/QCVGpvzcHko?t=146
Pushed an update and forgot to update this.
> Add ShadowUtilityLIB to yet another mod

- NetKAN/ToggleNotifications.netkan
This ZIP's structure has changed. Now we'll use a regexp that should match both formats.
- <https://github.com/cvusmo/Toggle-Notifications>
- <https://spacedock.info/mod/3377/Toggle%20Notifications>
> Fix ToggleNotifications install

- NetKAN/SpaceWarp.netkan
> Add UITKforKSP2 depends for SpaceWarp

- NetKAN/CommunityFixes.netkan
Folder structure changed.
___
ckan compat add 0.1.2
> Update CommunityFixes install

- NetKAN/FlightPlan.netkan
> Update FlightPlan dependencies

- NetKAN/MicroEngineer.netkan
> Update MicroEngineer dependencies

- NetKAN/ManeuverNodeController.netkan
> Update ManeuverNodeController dependencies

- NetKAN/TillDusk.netkan
The folder structure has changed.
> Update TillDusk install

- NetKAN/FancyFuelTanks.netkan
This mod just added a `swinfo.json` file.
- <https://spacedock.info/mod/3431/Fancy%20Fuel%20Tanks>
- <https://github.com/cvusmo/FFT>
- <https://forum.kerbalspaceprogram.com/topic/218451-fancy-fuel-tanks-fft-012-released/>
> Vref for FancyFuelTanks

- NetKAN/FancyFuelTanks.netkan
This mod now includes its version number in the folder name.
> Update FancyFuelTanks install

- NetKAN/FancyFuelTanks.netkan
SpaceDock is giving this author a hard time with uploading, and they've expressed an interest in switching to the GitHub download. This PR does that.
https://github.com/cvusmo/FFT
Hello and FYI to @cvusmo / @blacksheepcosmo. 👋
> Switch FancyFuelTanks kref to GitHub

- NetKAN/KESASolar.netkan
The folder structure has changed.
https://spacedock.info/mod/3453/Kesa%20Solar
> Fix KESASolar install

- NetKAN/Kesa.netkan
> LFO dep for Kesa

- NetKAN/HideOrbits.netkan
> Fix HideOrbits install

- NetKAN/Reflektor.netkan
Reflektor is a quick and powerful alternative to unity explorer for browsing and editing KSP2 objects, useful for mod developers.
https://github.com/coldrifting/Reflektor
> Add Reflektor

- NetKAN/TextAssetDumper
A tool for modders to dump all text assets from addressables and all localizations.
> Add TextAssetDumper

- NetKAN/DarkMode.netkan
Dark Mode is a UI mod that applies a dark theme to the KSC windows
> Add DarkMode

- NetKAN/SPARKTechnologies.netkan
New dependency on Patch Manager
> Add SPARKTechnologies dependency

- NetKAN/TheNuclearOption.netkan
New dependency on Patch Manager
> Add TheNuclearOption dependency

- NetKAN/CelestialGlow.netkan
I forgot to do this when adding it this morning
> Add github download to celestial glow

- NetKAN/WayfarersWingsRankRibbons.netkan
Add version edit to wayfarers wings
> Add version edit to wayfarers wings

- NetKAN/WASDForVAB.netkan
This mod's folder structure has changed.
> Fix WASDForVAB install

- NetKAN/SpringCleaning.netkan
missed this in it's dependencies
> Add missing dependency on premonition for spring cleaning

- NetKAN/KESASolar.netkan
This mod's folder name has changed.
> Update KESASolar folder name

- NetKAN/SASed-Warp.netkan
This mod's folder name has changed.
> Update SASed-Warp install

- NetKAN/KSRe.netkan
- <https://sourceforge.net/projects/ksre/>
See KSP-CKAN/CKAN#4172 for the creation of SourceForge krefs.
> Unfreeze KSRe with SourceForge kref
